---
azs:
- name: z1
vm_types:
- name: minimal
  cloud_properties:
    cpu: 2
    ram: 1024
    disk: 3240
- name: small
  cloud_properties:
    cpu: 2
    ram: 1024
    disk: 3240
- name: small-highmem
  cloud_properties:
    cpu: 2
    ram: 4096
    disk: 30_240

disk_types:
- name: default
  disk_size: 3000
- name: 10240
  disk_size: 10_240
- name: 5120
  disk_size: 5_120
networks:
- name: default
  type: manual
  subnets:
  - range: 10.244.0.0/24
    gateway: 10.244.0.1
    azs: [z1]
    dns: [8.8.8.8]
    static : [10.244.0.12-10.244.0.20]
compilation:
  workers: 2
  reuse_compilation_vms: true
  az: z1
  vm_type: small-highmem
  network: default
