---
name: mariadb                      # 서비스 배포이름(필수) bosh deployments 로 확인 가능한 이름

stemcells:
- alias: default
  os: ubuntu-xenial
  version: latest

releases:
- name: mariadb                   # 서비스 릴리즈 이름(필수) bosh releases로 확인 가능
  version: latest                                              # 서비스 릴리즈 버전(필수):latest 시 업로드된 서비스 릴리즈 최신버전

instance_groups:
- name: mariadb
  azs: [z3]
  instances: 1
  vm_type: default
  stemcell: default
  persistent_disk_type: 5GB 
  networks:
  - name: default

  jobs:
  - name: mariadb
    release: mariadb
    properties:
      mariadb:
        port: ((mariadb_port))                                        #InfluxDB default database
        admin_user:
          password: '((mariadb_user_password))'                             # MARIA DB ROOT 계정 비밀번호

update:
  canaries: 1
  canary_watch_time: 1000-180000
  max_in_flight: 1
  serial: true
  update_watch_time: 1000-180000

