apiVersion: v1
kind: Pod
metadata:
  name: hello-node
  labels:
    app: hello-node
spec:
  containers:
  - name: gs-spring-boot-docker
    image: springio/gs-spring-boot-docker
    ports:
    - name: nodejs-port
      containerPort: 8080
