apiVersion: v1
kind: Service
metadata:
  name: hello-node-svc
spec:
  selector:
    app: hello-node
#  type: NodePort
  type: LoadBalancer 
  ports:
  - name: http 
    port: 80
    nodePort: 30036
    targetPort: 8080
    protocol: TCP

