apiVersion: v1
kind: Service
metadata:
  name: replica-set-svc
spec:
  selector:
    app: guestbook
#  type: NodePort
  type: LoadBalancer 
  ports:
  - name: http 
    port: 80
    nodePort: 30036
    targetPort: 8080
    protocol: TCP

